# Generated by Django 5.1.1 on 2024-10-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teams",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
